title: Varshini Srinivas # your name (or website title) here
logo: "images/polaroid_headshot_fancy2.gif?raw=true" # your photo (or logo) here
description: >
  <div style="text-align: center; font-size: 12px; margin-top: -10px;">  <!-- Reduced space between logo and description -->
    <strong>Hi, Iâ€™m Varshi! ğŸ‘‹</strong>
    <br><br> <!-- Line space between intro and body -->
    Iâ€™m a data scientist with a background in consulting, industrial engineering, and operations research. I specialize in turning data into stories using ğŸ Python, ğŸ“Š Tableau, and ğŸ’¾ SQL.  
    In my spare time, I love to ğŸ³ <a href="https://www.instagram.com/chubbymonkii/?hl=en">cook</a>, make ğŸ¨ <a href="https://www.etsy.com/shop/StudioVarshi">linocut prints</a>, and volunteer with ğŸ¾ <a href="https://muttville.org/about_us?hl=en">Muttville SF</a>!
  </div>

  <style>
    .icon {
      color: #00badf; /* Original color */
      font-size: 39px; /* Smaller size */
      cursor: pointer;
      margin: 0 10px; /* Spacing around icons */
      transition: color 0.3s; /* Smooth transition */
    }
    .icon a {
      color: inherit; /* Use the parent color */
      text-decoration: none; /* Remove underline */
    }
    .icon:hover {
      color: #72d9ff; /* Lighter blue on hover */
    }
    .icon-container {
      display: flex;
      justify-content: center; /* Center the icons */
      align-items: center; /* Center vertically */
      width: 100%; /* Full width of the header */
    }
  </style>
  
  <div class="icon-container">
    <span title="Copy email: battler_haft_0h@icloud.com" class="icon">
      <a href="mailto:battler_haft_0h@icloud.com">
        <i class="fas fa-envelope"></i>
      </a>
    </span>
    <span title="View My LinkedIn Profile" class="icon">
      <a href="https://www.linkedin.com/in/sriniv37/" target="_blank">
        <i class="fab fa-linkedin"></i>
      </a>
    </span>
    <span title="Download My Resume" class="icon">
      <a href="https://drive.google.com/file/d/13j1rDjqDtEbl6GNtLmQfVSdhPL02XMKd/view?usp=sharing" target="_blank">
        <i class="fas fa-file-download"></i>
      </a>
    </span>
    <span title="View My GitHub Profile" class="icon">
      <a href="https://github.com/v4rshi" target="_blank">
        <i class="fab fa-github"></i>
      </a>
    </span>
  </div>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
